---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: test-task-deploy
  name: mindbox-deploy-webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      type: test-task-pod
  template:
    #вешаем label на под (ДОЛЖЕН БЫТЬ такой же, как и на селекторе)
    metadata:
      labels:
        type: test-task-pod
    #спецификация пода
    spec:
      containers:
      - image: nginx:1.16.1
        name: nginx
        resources:
          requests:
            # в вводных дано, что требуется минимум 0.1 CPU, поэтому просим sheduler найти ноду, которая точна предоставит 0.1 CPU
            cpu: "100m"
            # в вводных дано, что потребление memory "ровно" в районе 128М, поэтому запрашиваем ноду, которая может предоставить столько памяти
            memory: "128M"
          limits:
            # не уточнено насколько возрастает потребление CPU на первые запросы - лимит на CPU не ставлю
            # потребление памяти "ровное" в районе 128М - лимит поставлю с запасом (+25%), т.к. мне не известна окрестность района :)
            memory: "160M"
          
      affinity:
        podAntiAffinity:
          #т.к. кластер мультизонный и требуется fault-tolerance, то стоит распределить поды на разные ноды
          requiredDuringSchedulingIgnoredDuringExecution:
            #говорим sheduler, чтобы не размещал поды с label "test-task-pod" на одной ноде
            - labelSelector:
                matchExpressions:
                  - key: "type"
                    operator: In
                    values:
                    - test-task-pod
              topologyKey: "kubernetes.io/hostname"